name: nusantara_dash
description: "Nusantara Dash - 2D Runner Edutainment Budaya Indonesia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Game Engine
  flame: ^1.35.1
  
  # Save Data Lokal (progres pulau, kunci, koin)
  shared_preferences: ^2.5.5
  
  # Video Player (untuk cutscene)
  video_player: ^2.8.1

  # Audio (BGM)
  audioplayers: ^6.1.0 #Untuk BGM
  google_fonts: ^6.1.0 #Untuk pixel font

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    # Player
    - assets/images/player/
    
    # Boss
    - assets/images/boss/final/
    - assets/images/boss/mini/
    
    # Video (cutscene)
    - assets/videos/
    
    # BGM
    - assets/audio/bgm/

    # Background
    - assets/images/background/
    
    # Obstacles
    - assets/images/obstacles/
    
    # Items
    - assets/images/items/
    
    # Weapons
    - assets/images/weapons/
    
    # UI
    - assets/images/ui/
    
    # Data
    - assets/data/quiz_data.json
    - assets/data/province_config.json
    - assets/data/weapon_data.json