name: nusantara_dash
description: "Nusantara Dash - 2D Runner Edutainment Budaya Indonesia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 🎮 Game Engine
  flame: ^1.35.1
  
  # 💾 Save Data Lokal
  shared_preferences: ^2.5.5
  
  # 🎬 Video Player
  video_player: ^2.8.1

  # 🎵 Audio
  audioplayers: ^6.1.0
  
  # 🔤 Font
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ✅ Tambahkan package icon di sini
  flutter_launcher_icons: "^0.14.2"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/player/
    - assets/images/boss/final/
    - assets/images/boss/mini/
    - assets/videos/
    - assets/audio/bgm/
    - assets/images/background/
    - assets/images/obstacles/
    - assets/images/items/
    - assets/images/weapons/
    - assets/images/ui/
    - assets/data/quiz_data.json
    - assets/data/province_config.json
    - assets/data/weapon_data.json

# ✅ Konfigurasi Icon (Blok ini harus di paling bawah)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ui/nusantara_logo.jpg"
  min_sdk_android: 21